### ISSUE TITLE
SDK 22 Questions

### ISSUE THREAD

**Issue by ryanhomer** [expo/expo-docs#194]
I've just updated to SDK 22, deleted `node_modules` and did a fresh `npm install`. I'm getting the following 2 warnings:
```
npm ERR! peer dep missing: react@>=15.4.0, required by react-native-branch@2.0.0-beta.3
npm ERR! peer dep missing: react@> 15.0.0, required by react-native-gesture-handler@1.0.0-alpha.28
```

1. Is this expected and can I safely ignore these warnings?
1. Also, are you still recommending we use npm v4.6.1?

**Comment by brentvatne** [comment]
Hi @ryanhomer!

Peer dependency warnings are pretty annoying and caused by npm's opinion on semantic versioning should work for peer dependencies -- according to npm, >= 15.0.0 does not match 16.0.0-beta.5, and so you see this warning. Yarn handles this better, in my opinion, and doesn't give you a peer dependency warning for this case. See this issue for more info: https://github.com/npm/npm/issues/8854
