### ISSUE TITLE
Saving to phone gallery from expo camera 

### ISSUE THREAD

**Issue by JustinJKlein** [expo/expo-docs#289]
I am having trouble saving the pictures I am taking with my app to the gallery of my phone. I really believe that the basic implementation docs for this should include this portion of functionality. Right now there is not a ton of documentation available on how to do this external to your docs.

I am able to see the pictures I have taken when I hit gallery within the app but when I hit save to gallery I get this warning and no functionality >
possible unhandled promise rejection (id:1) undefined is not an object

**Comment by jimmylee** [comment]
Hey @JustinJKlein !

The best place to get help for this problem is at https://forums.expo.io or https://slack.expo.io. If you post your question there I'm pretty sure someone will get to it.

I'll keep an eye out for your question and try to update the docs here as well. Closing this for now, but feel free to open a new issue once you've solved your problem and you want to share how the docs could be improved.
