### ISSUE TITLE
Outdated documentation for 'Using Firebase'

### ISSUE THREAD

**Issue by nikhilag** [expo/expo-docs#47]
The documentation for 'Using Firebase' at https://docs.expo.io/versions/v15.0.0/guides/using-firebase.html mentions the following:-

> Note: This guide only covers Firebase Realtime Database, and not the other services under the larger Google Firebase umbrella. Firebase Cloud Storage is currently not supported, but we are working on upstreaming a Blob implementation to React Native that would make this possible. This will likely be available in SDK14.

Since SDK15 is already out, we should update the documentation. Also, is Firebase Cloud Storage supported now?

**Comment by brentvatne** [comment]
It turns out that it didn't land for SDK14 because it has taken a long time for this to be reviewed upstream. Firebase Cloud Storage is still not supported due to its usage of the Blob API - you can read about an alternative approach here: https://forums.expo.io/t/expo-and-uploading-image-blobs/227

You can monitor the progress of upstreaming the Blob API here:
- https://github.com/facebook/react-native/pull/11573
- https://github.com/facebook/react-native/pull/11417

**Comment by nikhilag** [comment]
Thanks! The following part does need to be changed in the documentation however:-

> This will likely be available in SDK14.

How about using https://github.com/fullstackreact/react-native-firestack?

**Comment by brentvatne** [comment]
@nikhilag - feel free to submit a PR if you think it's important :)

no interest in react-native-firestack be ecausas I mentioned above the Blob implementation upstream will fix the issue. It's better to depend on standards / low level primitives than specific native code for a service.

**Comment by brentvatne** [comment]
fixed this

**Comment by pavitran** [comment]
is this fixed?

**Comment by brentvatne** [comment]
no I just updated the documentation.

track the Blob support here: https://expo.canny.io/feature-requests/p/blob-support
